# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f2944e5c84a4ba0770e84471796507071a361b51bb981463c22490ebd91baa28c84879d1a1524efba1085b392d0c3733e8aebc98071671835b299df2dfa3a03

test:
  secret_key_base: 9e15a6628e41fa5b002124c77bf446825bc0042a190dd415fc5ba771b862942292f1c777b4eef822c21d8c25230249ff109e98f819d6eff63ff6b6c77bb7baf1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
